apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-broker
  namespace: observability
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      strimzi.io/pool-name: broker
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-controller
  namespace: observability
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      strimzi.io/pool-name: controller
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
