apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-observability
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: P8E80F9AEF21F6940
        access: proxy
        url: http://loki-gateway.observability.svc.cluster.local/
        isDefault: false
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          derivedFields:
            - name: TraceID
              matcherRegex: '"trace_id"\s*:\s*"(\w+)"'
              url: '$${__value.raw}'
              datasourceUid: P214B5B846CF3925F
        secureJsonData:
          httpHeaderValue1: homeplate

      - name: Tempo
        type: tempo
        uid: P214B5B846CF3925F
        access: proxy
        url: http://tempo-query-frontend.observability.svc.cluster.local:3200
        isDefault: false
        jsonData:
          httpMethod: GET
          serviceMap:
            datasourceUid: prometheus
          tracesToLogsV2:
            datasourceUid: P8E80F9AEF21F6940
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: false
            filterBySpanID: false
            customQuery: true
            query: '{service_name="$${__span.tags["service.name"]}"} | json | trace_id="$${__trace.traceId}"'
          tracesToMetrics:
            datasourceUid: prometheus