apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: observability-secretsmanager
  namespace: observability
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2