apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-webhooks
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: observability-secretsmanager
    kind: SecretStore
  target:
    name: alertmanager-webhooks
    creationPolicy: Owner
  data:
    - secretKey: slack_critical_url
      remoteRef:
        key: alertmanager-webhooks
        property: slack_critical_url
    - secretKey: slack_warning_url
      remoteRef:
        key: alertmanager-webhooks
        property: slack_warning_url
    - secretKey: aiops_url
      remoteRef:
        key: alertmanager-webhooks
        property: aiops_url