apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aiops-backend
  namespace: aiops
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: aiops-backend
  namespaceSelector:
    matchNames:
      - aiops
  endpoints:
    - port: http
      path: /metrics
      interval: 60s