apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy-logs
  namespace: observability
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: alloy-logs
      app.kubernetes.io/name: alloy
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 60s