apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aiops-backend-db
  namespace: aiops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aiops-secretsmanager
    kind: SecretStore
  target:
    name: aiops-backend-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: aiops/rds/aiops-postgres/app
        property: password