apiVersion: v1
kind: Service
metadata:
  name: aws-load-balancer-controller-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
spec:
  selector:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
  ports:
    - name: http-metrics
      port: 8080
      targetPort: metrics-server